---
# tasks file for roles/command
- name: 关闭firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no
- name: 关闭selinux
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX=.*'
    line: SELINUX=disabled
- name: 关闭swap
  lineinfile:
    path: /etc/fstab
    regexp: '.*swap.*'
    line: ''
- name: 临时关闭
  shell: setenforce 0; swap -a
- name: 更改时区
  copy:
    src: /usr/share/zoneinfo/Asia/Shanghai
    dest: /etc/localtime
- name: 更改hosts
  template: 
    src: hosts.j2
    dest: /opt/hosts
- name: 修改yum原
  shell: curl -o /etc/yum.repos.d/CentOS-Base.repo https://mirrors.aliyun.com/repo/Centos-7.repo && yum makecache
- name: 安装ntpdate
  yum:
    name: "{{ package }}"
    state: present
  vars:
    package:
    - ntpdate
    - wget
- name: 同步时间
  shell: ntpdate time.windows.com
- name: 修改主机名
  hostname:
    name: '{{ node_name }}'
#- name: test
#  debug:
#    msg: '{{ node_name }}'
